const express=require("express"),path=require("path"),fs=require("fs"),crypto=require("crypto"),session=require("express-session"),bcrypt=require("bcryptjs"),Database=require("better-sqlite3"),multer=require("multer");
const Razorpay=require("razorpay"),app=express(),db=new Database("companionday.db");
const PORT=process.env.PORT||3000, FEE=Number(process.env.REGISTRATION_FEE_PAISE||49900);
fs.mkdirSync(path.join(__dirname,"public","uploads"),{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:(r,f,cb)=>cb(null,path.join(__dirname,"public","uploads")),filename:(r,f,cb)=>cb(null,Date.now()+"-"+crypto.randomBytes(5).toString("hex")+"-"+f.originalname.replace(/[^a-zA-Z0-9._-]/g,"_"))}),limits:{fileSize:5*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^image\/(jpeg|png|webp)$/.test(f.mimetype))});
app.use(express.json());app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||"CHANGE_ME",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:false,maxAge:86400000}}));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL UNIQUE,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,paid INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS companions(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,age INTEGER,city TEXT,price INTEGER,activities TEXT,bio TEXT,photo TEXT,verified INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,companion_id INTEGER,booking_date TEXT,hours INTEGER,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
let rzp=null;if(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET&&process.env.RAZORPAY_KEY_ID!=="your_razorpay_key_id")rzp=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});
function admin(req,res,next){if(req.session.admin)return next();res.status(401).json({error:"Admin login required"});}
function user(req,res,next){if(req.session.user)return next();res.status(401).json({error:"Login required"});}
function pending(req,res,next){if(req.session.pendingUser)return next();res.status(401).json({error:"Registration session expired"});}
app.use(express.static(path.join(__dirname,"public")));
app.get("/api/me",(req,res)=>res.json({user:req.session.user||null}));
app.post("/api/register",async(req,res)=>{const {name,phone,email,password}=req.body||{};if(!name||!phone||!email||!password)return res.status(400).json({error:"All fields are required"});if(password.length<8)return res.status(400).json({error:"Password must be at least 8 characters"});try{const h=await bcrypt.hash(password,12),i=db.prepare("INSERT INTO users(name,phone,email,password_hash) VALUES(?,?,?,?)").run(name.trim(),phone.trim(),email.trim().toLowerCase(),h),u=db.prepare("SELECT id,name,email,paid FROM users WHERE id=?").get(i.lastInsertRowid);req.session.pendingUser=u;if(!rzp)return res.status(503).json({error:"Razorpay is not configured. Add keys to .env."});const o=await rzp.orders.create({amount:FEE,currency:"INR",receipt:"reg_"+u.id,payment_capture:1});res.json({user:u,order:o,keyId:process.env.RAZORPAY_KEY_ID});}catch(e){res.status(409).json({error:"Email or phone may already be registered"});}});
app.post("/api/payment-success",pending,(req,res)=>{if(!req.body.razorpay_payment_id)return res.status(400).json({error:"Payment confirmation missing"});const id=req.session.pendingUser.id;db.prepare("UPDATE users SET paid=1 WHERE id=?").run(id);const u=db.prepare("SELECT id,name,email,paid FROM users WHERE id=?").get(id);req.session.user=u;delete req.session.pendingUser;res.json({ok:true,user:u});});
app.post("/api/login",async(req,res)=>{const u=db.prepare("SELECT * FROM users WHERE email=?").get((req.body.email||"").toLowerCase());if(!u||!await bcrypt.compare(req.body.password||"",u.password_hash))return res.status(401).json({error:"Invalid email or password"});if(!u.paid)return res.status(403).json({error:"Complete the ₹499 registration payment first"});req.session.user={id:u.id,name:u.name,email:u.email,paid:1};res.json({ok:true,user:req.session.user});});
app.post("/api/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/companions",(req,res)=>res.json(db.prepare("SELECT * FROM companions ORDER BY id DESC").all()));
app.post("/api/bookings",user,(req,res)=>{const {companion_id,booking_date,hours}=req.body;if(!companion_id||!booking_date||!hours)return res.status(400).json({error:"Select companion, date and duration"});db.prepare("INSERT INTO bookings(user_id,companion_id,booking_date,hours) VALUES(?,?,?,?)").run(req.session.user.id,companion_id,booking_date,Number(hours));res.json({ok:true});});
app.get("/api/admin/me",(req,res)=>res.json({admin:!!req.session.admin}));
app.post("/api/admin/login",(req,res)=>{if(req.body.username===(process.env.ADMIN_USER||"admin")&&req.body.password===(process.env.ADMIN_PASS||"CHANGE_THIS_PASSWORD")){req.session.admin=true;return res.json({ok:true})}res.status(401).json({error:"Invalid admin credentials"});});
app.post("/api/admin/logout",admin,(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.post("/api/admin/companions",admin,upload.single("photo"),(req,res)=>{const {name,age,city,price,activities,bio,verified}=req.body;if(!name||Number(age)<18||!city||!price)return res.status(400).json({error:"Name, age (18+), city and price are required"});const photo=req.file?"/uploads/"+req.file.filename:null;db.prepare("INSERT INTO companions(name,age,city,price,activities,bio,photo,verified) VALUES(?,?,?,?,?,?,?,?)").run(name,age,city,price,activities||"",bio||"",photo,verified==="1"?1:0);res.json({ok:true});});
app.patch("/api/admin/companions/:id",admin,(req,res)=>{const c=db.prepare("SELECT * FROM companions WHERE id=?").get(req.params.id);if(!c)return res.status(404).json({error:"Not found"});const v=req.body.verified?1:0;db.prepare("UPDATE companions SET verified=? WHERE id=?").run(v,c.id);res.json({ok:true});});
app.delete("/api/admin/companions/:id",admin,(req,res)=>{const c=db.prepare("SELECT photo FROM companions WHERE id=?").get(req.params.id);if(c?.photo)try{fs.unlinkSync(path.join(__dirname,"public",c.photo))}catch{}db.prepare("DELETE FROM companions WHERE id=?").run(req.params.id);res.json({ok:true});});
app.get("/api/admin/bookings",admin,(req,res)=>res.json(db.prepare("SELECT b.*,u.name user_name,u.phone,u.email,c.name companion_name FROM bookings b JOIN users u ON u.id=b.user_id JOIN companions c ON c.id=b.companion_id ORDER BY b.id DESC").all()));
app.listen(PORT,()=>console.log("CompanionDay running on "+PORT));
